[tcpdp]
pidfile = "/var/run/tcpdp/<%= @if %>.pid"
dumper = "mysql"

[probe]
target = "3306"
interface = "<%= @if %>"
bufferSize = "128MB"
immediateMode = true

[log]
dir = "/var/log/tcpdp/<%= @if %>"
enable = true
format = "json"
rotateEnable = true
rotationTime = "daily"
rotationCount = 3
<% if @log_rotation_hook_script -%>
rotationHook = "<%= log_rotation_hook_script %>"
<% end -%>

[dumpLog]
dir = "/var/log/tcpdp/<%= @if %>"
enable = true
format = "json"
rotateEnable = true
rotationTime = "daily"
rotationCount = 3
<% if @dump_rotation_hook_script -%>
rotationHook = "<%= dump_rotation_hook_script %>"
<% end -%>
